# serializers.py

from rest_framework import serializers

class UserQuerySerializer(serializers.Serializer):
    query = serializers.CharField(required=True, allow_blank=False, help_text="The search query for the user.")
    user_id = serializers.IntegerField(required=True, help_text="The ID of the user to base the query on.")

class UserQueryResponseSerializer(serializers.Serializer):
    response = serializers.CharField(help_text="Response generated by the SQL agent.")
    sql_query = serializers.CharField(help_text="The SQL query executed.")

class UserSummarySerializer(serializers.Serializer):
    request_id = serializers.CharField(required=True, help_text="The ID of the request to summarize.")

class UserSummaryResponseSerializer(serializers.Serializer):
    response = serializers.CharField(help_text="Summary of the documents associated with the request.")
