# Generated by Django 5.1.2 on 2024-11-03 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('clinic', 'Clinic'), ('dentist', 'Dentist'), ('hospital', 'Hospital'), ('psychologist', 'Psychologist'), ('therapist', 'Therapist'), ('pharmacy', 'Pharmacy')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alinea_api.entity')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('personal_info', 'Personal Information'), ('medical_info', 'Medical Information'), ('dental_questionnaire', 'Dental Questionnaire'), ('psychological_info', 'Psychological Information')], max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alinea_api.accessrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DentalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_dental_visit', models.DateField(blank=True, null=True)),
                ('reason_for_last_visit', models.CharField(blank=True, max_length=255)),
                ('brushing_frequency', models.CharField(blank=True, max_length=50)),
                ('flossing_frequency', models.CharField(blank=True, max_length=50)),
                ('dental_issues', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='medical_records/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, choices=[('stable', 'Stable'), ('anxious', 'Anxious'), ('depressed', 'Depressed'), ('irritable', 'Irritable'), ('elevated', 'Elevated')], max_length=20)),
                ('stress_level', models.IntegerField(blank=True, help_text='Scale from 1 (low stress) to 10 (high stress)', null=True)),
                ('sleep_quality', models.IntegerField(blank=True, help_text='Scale from 1 (poor sleep) to 10 (excellent sleep)', null=True)),
                ('mental_health_history', models.TextField(blank=True, help_text='Past mental health diagnoses or treatments')),
                ('current_symptoms', models.TextField(blank=True, help_text='Current mental health symptoms')),
                ('therapy_history', models.TextField(blank=True, help_text='Previous therapy or counseling experiences')),
                ('medications', models.TextField(blank=True, help_text='Current psychiatric medications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('surgeries', models.TextField(blank=True)),
                ('smoking_status', models.CharField(blank=True, choices=[('never_smoked', 'Never Smoked'), ('former_smoker', 'Former Smoker'), ('current_smoker', 'Current Smoker')], max_length=15)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('social_drinker', 'Social Drinker'), ('regular_drinker', 'Regular Drinker'), ('heavy_drinker', 'Heavy Drinker')], max_length=20)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('none', 'None'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('frequent', 'Frequent')], max_length=15)),
                ('medications', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('family_medical_history', models.TextField(blank=True)),
                ('immunizations', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
