# Generated by Django 5.1.2 on 2024-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alinea_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='timezone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
