# Generated by Django 5.1.2 on 2024-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alinea_api', '0002_entity_city_entity_country_entity_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
