# Generated by Django 5.1.2 on 2024-12-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alinea_api', '0003_template_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('entity', 'document_type', 'name')},
        ),
    ]
